### ISSUE TITLE
Custom width

### ISSUE THREAD

**Issue by RGPaul** [israelhudson/side_sheet#2]
Would be nice if we can set the width of the sheet.

**Comment by qwaiks** [comment]
sent out a PR to that effect so maybe he reviews and adds that as soon as possible.

**Comment by fabios9702** [comment]
news on this?

**Comment by israelhudson** [comment]
Hi everyone, there is an open pr about this and I will review it as soon as possible. Any news I communicate in this issue.

**Comment by israelhudson** [comment]
Hello Devs! version 1.0.2 has been published on pub.dev with this improvement developed by @RGPaul. Thank you for everything!
